config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :posts
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
  end

  def edit
  @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :body))
    @post.save
    redirect_to @post
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params.require(:post).permit(:title, :body))
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

<p>

<%= f.label :title %><br>

<%= f.text_field :title %>

</p>



<p>

<%= f.label :body %><br>

<%= f.text_area :body %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<%= link_to 'New Post', new_post_path %>
<table>

<tr>

<th>Title</th>

<th>Body</th>

</tr>

<% @posts.each do |post| %>

<tr>

<td><%= post.title %></td>

<td><%= post.body %></td>

<td><%= link_to 'Show', post_path(post) %></td>
<td><%= link_to 'Edit', edit_post_path(post) %></td>

<td><%= link_to 'Destroy', post_path(post),

method: :delete,

data: { confirm: 'Are you sure?' } %></td>

</tr>

<% end %>

</table>

app/views/posts/new.html.erb
<%= form_for :post, url:posts_path do |f| %>

<p>

<%= f.label :title %><br>

<%= f.text_field :title %>

</p>



<p>

<%= f.label :body %><br>

<%= f.text_area :body %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/posts/show.html.erb
<p>

<strong>Title:</strong>

<%= @post.title %>

</p>

<p>

<strong>Body:</strong>

<%= @post.body %>

</p>

<%= link_to 'Edit', edit_post_path(@post) %>

<%= link_to 'Destroy', post_path(@post),

method: :delete,

data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<p>
  hello world
</p>